name: "Build Armbian Installer ISO"

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "版本类型"
        required: true
        default: "armbian-ubuntu24_minimal"
        type: choice
        options:
          - "standard"
          - "armbian-debian13_minimal"
          - "armbian-ubuntu24_minimal"
          - "armbian-homeassistant_debian12_minimal"
          - "DietPi_debian13"

jobs:
  build-release:
    runs-on: ubuntu-22.04
    env:
      VERSION_TYPE: ${{ github.event.inputs.version_type }}

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: ./build.sh

      - name: "Prepare Release Assets"
        run: |
          # 根据版本类型重命名ISO文件
          if [ "$VERSION_TYPE" = "armbian-debian13_minimal" ]; then
            mv output/armbian-installer-x86_64-standard.iso output/armbian-installer-x86_64-debian13_minimal.iso
          fi

          if [ "$VERSION_TYPE" = "armbian-ubuntu24_minimal" ]; then
            mv output/armbian-installer-x86_64-standard.iso output/armbian-ubuntu24_minimal-installer-x86_64.iso
          fi

          if [ "$VERSION_TYPE" = "DietPi_debian13" ]; then
            mv output/armbian-installer-x86_64-standard.iso output/DietPi_debian13-installer-x86_64.iso
          fi
          
          if [ "$VERSION_TYPE" = "armbian-homeassistant_debian12_minimal" ]; then
            mv output/armbian-installer-x86_64-standard.iso output/armbia-homeassistant_debian12_minimal-installer-x86_64.iso
          fi
          

      - name: "Publish"
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "Armbian-Installer-x86_64-ISO"
          body_path: ${{ github.workspace }}/info.md
          files: |
            output/${{ github.event.inputs.version_type }}-installer-x86_64.iso
          token: ${{ secrets.GITHUB_TOKEN }}
